using System;
using UnityEngine;
using Object = UnityEngine.Object;

namespace Monogum.BricksBucket.Core.Generics
{
    /// <summary>
    /// Dynamic reference to component properties.
    /// </summary>
    /// <typeparam name="TRegistry">Type of the hardwired script inheritor.
    /// </typeparam>
    [Serializable]
    public abstract class AbstractPropertyReference<TRegistry> :
        IPropertyReference
        where TRegistry : AbstractComponentRegistry, new()
    {

        #region Fields

        /// <summary>
        /// Instance of hardwired class.
        /// </summary>
        private static TRegistry _hardwired = new TRegistry();

        /// <summary>
        /// Reference to the instance object.
        /// </summary>
        [SerializeField]
        private Object component;

        /// <summary>
        /// Name of the property of the component.
        /// </summary>
        [SerializeField]
        private string property;

        #endregion


        #region Accessors

        /// <inheritdoc cref="IPropertyReference.Component"/>
        public Object Component
        {
            get => component;
            protected set => component = value;
        }

        /// <inheritdoc cref="IPropertyReference.Property"/>
        public string Property
        {
            get => property;
            protected set => property = value;
        }

        /// <summary>
        /// Instance of hardwired class.
        /// </summary>>
        /// <returns>Null if has not been assigned.</returns>
        public virtual IComponentRegistry Registry =>
            _hardwired ??= new TRegistry();
        
        /// <summary>
        /// Instance of ScriptData class.
        /// </summary>>
        /// <returns>Null if has not been assigned.</returns>
        public virtual IAutogeneratedScript ScriptData => 
            _hardwired ??= new TRegistry();


        #endregion


        #region Class Implementation

        /// <summary>
        /// Initializes a new instance of the AbstractReference class.
        /// </summary>
        protected AbstractPropertyReference()
        {
            Component = null;
            Property = string.Empty;
        }

        /// <inheritdoc cref="IPropertyReference.SetComponent"/>
        public void SetComponent(Object reference)
        {
            if (Component == reference) return;
            Component = reference;
            Property = string.Empty;
        }

        /// <inheritdoc cref="IPropertyReference.SetProperty"/>
        public void SetProperty(string propertyName)
        {
            if (Component == null) return;
            Property = propertyName;
        }

        /// <inheritdoc cref="IPropertyReference.GetPropertyType"/>
        public Type GetPropertyType()
        {
            var valid =
                _hardwired.ContainsComponent(Component) &&
                _hardwired.ContainsProperty(Component, Property);
            return !valid
                ? null
                : _hardwired.GetPropertyType(Component, Property);
        }

        /// <inheritdoc cref="IPropertyReference.GetValue"/>
        public object GetValue()
        {
            var valid =
                _hardwired.ContainsComponent(Component) &&
                _hardwired.ContainsProperty(Component, Property);
            return !valid ? null : _hardwired.GetValue(Component, Property);
        }

        /// <inheritdoc cref="IPropertyReference.SetValue"/>
        public void SetValue(object propertyValue)
        {
            var valid =
                _hardwired.ContainsComponent(Component) &&
                _hardwired.ContainsProperty(Component, Property);
            if (!valid) return;
            _hardwired.SetValue(Component, Property, propertyValue);
        }
        

        #endregion

    }
}