using System;
using UnityEngine;

namespace Monogum.BricksBucket.Core.Generics
{
    /// <!-- IReference -->
    /// <summary>
    /// Interface for a dynamic reference.
    /// </summary>
    public interface IPropertyReference
    {
        /// <summary>
        /// Reference to the instance object.
        /// </summary>
        /// <returns>A reference.</returns>
        Component Component { get; }
        
        /// <summary>
        /// Name of the property of the component.
        /// </summary>
        /// <returns>Null if has not been assigned.</returns>
        string Property { get; }
        
        /// <summary>
        /// System.Type of the value.
        /// </summary>
        /// <returns>Null if has not been assigned.</returns>
        Type ValueType { get; }
        
        /// <summary>
        /// Instance of hardwired class.
        /// </summary>>
        /// <returns>Null if has not been assigned.</returns>
        IComponentRegistry ComponentRegistry { get; }
        
        /// <summary>
        /// Instance of hardwired class.
        /// </summary>>
        /// <returns>Null if has not been assigned.</returns>
        IAutogeneratedScript ScriptData { get; }

        /// <summary>
        /// Gets the value of the variable.
        /// </summary>
        object GetValue();

        /// <summary>
        /// Sets the value of the property.
        /// </summary>
        void SetValue(object value);

        /// <summary>
        /// Sets the property.
        /// </summary>
        void SetProperty(string property);

        /// <summary>
        /// Set the object reference.
        /// </summary>
        /// <param name="reference">New reference.</param>
        void SetComponent(Component reference);
    }
}