using System;
using System.Collections.Generic;

/// <summary>
/// Registered types.
/// 
/// Since iOS cannot support System.Reflection, DynRef has to
/// have this static class to cast values.
/// 
/// 
/// <autogenerated>
/// 
/// This code was generated by a tool.
/// Changes to this file may cause incorrect behavior and will
/// be lost if the code is regenerated.
/// 
/// </autogenerated>
/// 
/// ----------------------------------------------------------
/// Code generated on Friday, 22 February 2019 13:11:07
/// ----------------------------------------------------------
///
/// By Javier García.
/// </summary>
public static class RegisteredTypes {

	/// <summary> Quickly view of all registered types. </summary>
	private static readonly List<Type> _typesList = new List<Type>{
		typeof(UnityEngine.GameObject),
		typeof(UnityEngine.RectTransform),
		typeof(UnityEngine.Transform)
	};

	/// <summary> Dictionary of actions to set values. </summary>
	private static readonly
	Dictionary<string, Dictionary<string, Action<object, object>>> _set =
		new Dictionary<string, Dictionary<string, Action<object, object>>> {
		{
			#region UnityEngine.GameObject
			"UnityEngine.GameObject",
			new Dictionary<string, Action<object, object>>{
				{"layer", (component, value) => (component as UnityEngine.GameObject).layer = (System.Int32)value},
				{"isStatic", (component, value) => (component as UnityEngine.GameObject).isStatic = (System.Boolean)value},
				{"tag", (component, value) => (component as UnityEngine.GameObject).tag = (System.String)value},
				{"name", (component, value) => (component as UnityEngine.GameObject).name = (System.String)value},
				{"hideFlags", (component, value) => (component as UnityEngine.GameObject).hideFlags = (UnityEngine.HideFlags)value}
			}
			#endregion
		},
		{
			#region UnityEngine.RectTransform
			"UnityEngine.RectTransform",
			new Dictionary<string, Action<object, object>>{
				{"anchorMin", (component, value) => (component as UnityEngine.RectTransform).anchorMin = (UnityEngine.Vector2)value},
				{"anchorMax", (component, value) => (component as UnityEngine.RectTransform).anchorMax = (UnityEngine.Vector2)value},
				{"anchoredPosition", (component, value) => (component as UnityEngine.RectTransform).anchoredPosition = (UnityEngine.Vector2)value},
				{"sizeDelta", (component, value) => (component as UnityEngine.RectTransform).sizeDelta = (UnityEngine.Vector2)value},
				{"pivot", (component, value) => (component as UnityEngine.RectTransform).pivot = (UnityEngine.Vector2)value},
				{"anchoredPosition3D", (component, value) => (component as UnityEngine.RectTransform).anchoredPosition3D = (UnityEngine.Vector3)value},
				{"offsetMin", (component, value) => (component as UnityEngine.RectTransform).offsetMin = (UnityEngine.Vector2)value},
				{"offsetMax", (component, value) => (component as UnityEngine.RectTransform).offsetMax = (UnityEngine.Vector2)value},
				{"position", (component, value) => (component as UnityEngine.RectTransform).position = (UnityEngine.Vector3)value},
				{"localPosition", (component, value) => (component as UnityEngine.RectTransform).localPosition = (UnityEngine.Vector3)value},
				{"eulerAngles", (component, value) => (component as UnityEngine.RectTransform).eulerAngles = (UnityEngine.Vector3)value},
				{"localEulerAngles", (component, value) => (component as UnityEngine.RectTransform).localEulerAngles = (UnityEngine.Vector3)value},
				{"right", (component, value) => (component as UnityEngine.RectTransform).right = (UnityEngine.Vector3)value},
				{"up", (component, value) => (component as UnityEngine.RectTransform).up = (UnityEngine.Vector3)value},
				{"forward", (component, value) => (component as UnityEngine.RectTransform).forward = (UnityEngine.Vector3)value},
				{"rotation", (component, value) => (component as UnityEngine.RectTransform).rotation = (UnityEngine.Quaternion)value},
				{"localRotation", (component, value) => (component as UnityEngine.RectTransform).localRotation = (UnityEngine.Quaternion)value},
				{"localScale", (component, value) => (component as UnityEngine.RectTransform).localScale = (UnityEngine.Vector3)value},
				{"parent", (component, value) => (component as UnityEngine.RectTransform).parent = (UnityEngine.Transform)value},
				{"hasChanged", (component, value) => (component as UnityEngine.RectTransform).hasChanged = (System.Boolean)value},
				{"hierarchyCapacity", (component, value) => (component as UnityEngine.RectTransform).hierarchyCapacity = (System.Int32)value},
				{"tag", (component, value) => (component as UnityEngine.RectTransform).tag = (System.String)value},
				{"name", (component, value) => (component as UnityEngine.RectTransform).name = (System.String)value},
				{"hideFlags", (component, value) => (component as UnityEngine.RectTransform).hideFlags = (UnityEngine.HideFlags)value}
			}
			#endregion
		},
		{
			#region UnityEngine.Transform
			"UnityEngine.Transform",
			new Dictionary<string, Action<object, object>>{
				{"position", (component, value) => (component as UnityEngine.Transform).position = (UnityEngine.Vector3)value},
				{"localPosition", (component, value) => (component as UnityEngine.Transform).localPosition = (UnityEngine.Vector3)value},
				{"eulerAngles", (component, value) => (component as UnityEngine.Transform).eulerAngles = (UnityEngine.Vector3)value},
				{"localEulerAngles", (component, value) => (component as UnityEngine.Transform).localEulerAngles = (UnityEngine.Vector3)value},
				{"right", (component, value) => (component as UnityEngine.Transform).right = (UnityEngine.Vector3)value},
				{"up", (component, value) => (component as UnityEngine.Transform).up = (UnityEngine.Vector3)value},
				{"forward", (component, value) => (component as UnityEngine.Transform).forward = (UnityEngine.Vector3)value},
				{"rotation", (component, value) => (component as UnityEngine.Transform).rotation = (UnityEngine.Quaternion)value},
				{"localRotation", (component, value) => (component as UnityEngine.Transform).localRotation = (UnityEngine.Quaternion)value},
				{"localScale", (component, value) => (component as UnityEngine.Transform).localScale = (UnityEngine.Vector3)value},
				{"parent", (component, value) => (component as UnityEngine.Transform).parent = (UnityEngine.Transform)value},
				{"hasChanged", (component, value) => (component as UnityEngine.Transform).hasChanged = (System.Boolean)value},
				{"hierarchyCapacity", (component, value) => (component as UnityEngine.Transform).hierarchyCapacity = (System.Int32)value},
				{"tag", (component, value) => (component as UnityEngine.Transform).tag = (System.String)value},
				{"name", (component, value) => (component as UnityEngine.Transform).name = (System.String)value},
				{"hideFlags", (component, value) => (component as UnityEngine.Transform).hideFlags = (UnityEngine.HideFlags)value}
			}
			#endregion
		}
	};

	/// <summary> Dictionary of functions to return values. </summary>
	private static readonly
	Dictionary<string, Dictionary<string, Func<object, object>>> _get =
		new Dictionary<string, Dictionary<string, Func<object, object>>> {
		{
			#region UnityEngine.GameObject
			"UnityEngine.GameObject",
			new Dictionary<string, Func<object, object>>{
				{"layer", (component) => (component as UnityEngine.GameObject).layer},
				{"isStatic", (component) => (component as UnityEngine.GameObject).isStatic},
				{"tag", (component) => (component as UnityEngine.GameObject).tag},
				{"name", (component) => (component as UnityEngine.GameObject).name},
				{"hideFlags", (component) => (component as UnityEngine.GameObject).hideFlags}
			}
			#endregion
		},
		{
			#region UnityEngine.RectTransform
			"UnityEngine.RectTransform",
			new Dictionary<string, Func<object, object>>{
				{"anchorMin", (component) => (component as UnityEngine.RectTransform).anchorMin},
				{"anchorMax", (component) => (component as UnityEngine.RectTransform).anchorMax},
				{"anchoredPosition", (component) => (component as UnityEngine.RectTransform).anchoredPosition},
				{"sizeDelta", (component) => (component as UnityEngine.RectTransform).sizeDelta},
				{"pivot", (component) => (component as UnityEngine.RectTransform).pivot},
				{"anchoredPosition3D", (component) => (component as UnityEngine.RectTransform).anchoredPosition3D},
				{"offsetMin", (component) => (component as UnityEngine.RectTransform).offsetMin},
				{"offsetMax", (component) => (component as UnityEngine.RectTransform).offsetMax},
				{"position", (component) => (component as UnityEngine.RectTransform).position},
				{"localPosition", (component) => (component as UnityEngine.RectTransform).localPosition},
				{"eulerAngles", (component) => (component as UnityEngine.RectTransform).eulerAngles},
				{"localEulerAngles", (component) => (component as UnityEngine.RectTransform).localEulerAngles},
				{"right", (component) => (component as UnityEngine.RectTransform).right},
				{"up", (component) => (component as UnityEngine.RectTransform).up},
				{"forward", (component) => (component as UnityEngine.RectTransform).forward},
				{"rotation", (component) => (component as UnityEngine.RectTransform).rotation},
				{"localRotation", (component) => (component as UnityEngine.RectTransform).localRotation},
				{"localScale", (component) => (component as UnityEngine.RectTransform).localScale},
				{"parent", (component) => (component as UnityEngine.RectTransform).parent},
				{"hasChanged", (component) => (component as UnityEngine.RectTransform).hasChanged},
				{"hierarchyCapacity", (component) => (component as UnityEngine.RectTransform).hierarchyCapacity},
				{"tag", (component) => (component as UnityEngine.RectTransform).tag},
				{"name", (component) => (component as UnityEngine.RectTransform).name},
				{"hideFlags", (component) => (component as UnityEngine.RectTransform).hideFlags}
			}
			#endregion
		},
		{
			#region UnityEngine.Transform
			"UnityEngine.Transform",
			new Dictionary<string, Func<object, object>>{
				{"position", (component) => (component as UnityEngine.Transform).position},
				{"localPosition", (component) => (component as UnityEngine.Transform).localPosition},
				{"eulerAngles", (component) => (component as UnityEngine.Transform).eulerAngles},
				{"localEulerAngles", (component) => (component as UnityEngine.Transform).localEulerAngles},
				{"right", (component) => (component as UnityEngine.Transform).right},
				{"up", (component) => (component as UnityEngine.Transform).up},
				{"forward", (component) => (component as UnityEngine.Transform).forward},
				{"rotation", (component) => (component as UnityEngine.Transform).rotation},
				{"localRotation", (component) => (component as UnityEngine.Transform).localRotation},
				{"localScale", (component) => (component as UnityEngine.Transform).localScale},
				{"parent", (component) => (component as UnityEngine.Transform).parent},
				{"hasChanged", (component) => (component as UnityEngine.Transform).hasChanged},
				{"hierarchyCapacity", (component) => (component as UnityEngine.Transform).hierarchyCapacity},
				{"tag", (component) => (component as UnityEngine.Transform).tag},
				{"name", (component) => (component as UnityEngine.Transform).name},
				{"hideFlags", (component) => (component as UnityEngine.Transform).hideFlags}
			}
			#endregion
		}
	};

	/// <summary>  The array of registered types. </summary>
	/// <value>The array.</value>
	public static Type[] Array {
		get { return _typesList.ToArray (); }
	}
	
	/// <summary> Contains the component. </summary>
	/// <returns><c>true</c>, if component is contained.</returns>
	/// <param name="component">Component.</param>
	public static bool ContainsComponent(string component){
		return
		_set.ContainsKey (component) &&
		_get.ContainsKey (component);
	}
	
	/// <summary> Contains the property. </summary>
	/// <returns><c>true</c>, if property is contained.</returns>
	/// <param name="component">Component.</param>
	/// <param name="property">Property name.</param>
	public static bool ContainsProperty(string component, string property) {
		return
			_set[component].ContainsKey (property) &&
			_get[component].ContainsKey (property);
	}
	
	/// <summary> Gets the value. </summary>
	/// <returns>The value.</returns>
	/// <param name="component">Component.</param>
	/// <param name="property">Property name.</param>
	public static object GetValue(object component, string property) {
		try {
			return _get[component.GetType ().ToString ()][property] (component);
		}
		catch(Exception exception){
			UnityEngine.Debug.LogError (exception);
			return null;
		}
	}
	
	/// <summary> Sets the value. </summary>
	/// <param name="component">Component.</param>
	/// <param name="property">Property name.</param>
	/// <param name="value">Value.</param>
	public static void SetValue (object component, string property, object value) {
		try {
			_set[component.GetType ().ToString ()][property] (component, value);
		}
		catch (Exception exception) {
			UnityEngine.Debug.LogError (exception);
		}
	}
}